### ISSUE TITLE
Logo for Cloud Create is needed

### ISSUE THREAD

**Issue by tischrei** [opentelekomcloud-docs/cloud-create#8]
Hi Tri,

we need a logo for Cloud Create for a proper visualization on main page: https://docs.otc.t-systems.com/index.html

KR
Tino

**Comment by trihoangvo** [comment]
![logo-cloud-create](https://github.com/opentelekomcloud-docs/cloud-create/assets/5804043/6884628a-e589-4d0e-8d48-7bdc9f1c6d0b)

Hi Tino,

Please find the logo in the attachment.

**Comment by tischrei** [comment]
Great, thanks. Has been added and will be merged in a minute.
